version: '3'
services:
  flask-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
